#********** Driver Parameters ************

/provider_underwater_com/connection/tty_port: "/dev/ttyUSB0"

/provider_underwater_com/settings/role : "master"

/provider_underwater_com/settings/channel : "4"